controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    gripper_controller:
      type: effort_controllers/GripperActionController

gripper_controller:
  ros__parameters:
    joint: gripper_joint
    goal_tolerance: 0.001
    max_effort: 100.0
    allow_stalling: true    # Set to TRUE to report SUCCEEDED when grasping an object!
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
    
    # PID GAINS FOR GRIPPER CONTROLLER:
    gains:
      gripper_joint:
        p: 100.0
        i: 5.0
        d: 10.0

# Legacy gazebo_ros2_control PID section removed as it is no longer required.